export const SemanticColor = {
  STRUCTURE: "#DCE7F5",
  RISK: "#F5C8C5",
  ARGUMENT: "#F6DEB8",

  FUNCTIONAL: "#C8E6D0",
  TECHNICAL: "#C7DCF3",
  SOFTWARE: "#DDD3F0",
  HARDWARE: "#DCDCDC",

  ASSUMPTION: "#E9C9E1",
  EVIDENCE: "#F7F0BF",
  DOCUMENTATION: "#C6E8E2",

  PROCESS: "#E9D3D3",
  METRIC: "#F5DABF",

  SUCCESS: "#BFE7C6",
  DANGER: "#F2B8B5",
} as const;